<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CubeVault.Application\CubeVault.Application.csproj" />
    <ProjectReference Include="..\CubeVault.Domain\CubeVault.Domain.csproj" />
    <ProjectReference Include="..\CubeVault.Infrastructure\CubeVault.Infrastructure.csproj" />
    <ProjectReference Include="..\CubeVault.Shared\CubeVault.Shared.csproj" />
  </ItemGroup>

</Project>